language: python
python:
- '3.5'
install:
- sudo apt-get update
- sudo apt-get install libcairo2-dev libnetpbm10-dev netpbm libpng12-dev libjpeg-dev
  zlib1g-dev libbz2-dev swig cfitsio-dev
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml --quiet
- source activate digicampipe
- pip install .
script:
- pytest digicampipe
- make -C docs/ html
- |
  if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
    pytest -c all_tests.ini
  fi
env:
  global:
  - GITHUB_REPO: github.com/cta-sst-1m/digicampipe.git
  - secure: kLTHK+/IvcLsozvC7cpphcn7MDSlKY0GTAYjlB/R4kR5BTlMVUJXVEYz1JPjUqdMQFu4OgurwAOi6P6G9Z3bhaBCMS9gBozEEOTWdtbc230NoSC3D02H+LPkYpmAvjMx9sW2l2rbSD03okXc/TK+IEcbBkosb/4fOB+YM77zWQ6JeDHrbDX11bFuLk2LbErCOal9Nxpiex6+6KDUyLVdxV4wcdOrTOJkCRL4/fJOUBejX1JGClpUMbMosxlFz+tcJ5hrLP9XFzfyMrcND3LBItjORJfD5VPdGCrNqAAHO0n0NT+TqTPwcoaMEXjhOm3lYw2u2kq8LEqBa1f5BxehR6y04xFy60QM7wyqYLg/C9TpYsCsp4iFvKAKcqn1IvBKV9P6xgPCGmgGf7a5YeoBcMMowatT7GKwCeF44TpBYl1lew2WxKWhtpmwjzsC5D6hJXxAkMAf96SIEK5J+cfeWI0T57eEfZlU0j/0ztxnlzIHkhre8oacUUlEGE2vxRLVEvr7GCfj81SpuRbyw0Yi+QtYF5VPNCUsNnTk7HUGPvUpmXo1ZCzn0FJ2NvFV2gd4MERHYK9WISR9wSeWEt4yTJ2N4pTFvxzHCEzL0uzCv0tpnVUVv2YfPu0hBHhVBHHPd3A3nCRIs9UuXN+O61aYEKwdFrC1yRiWMBBT+ZLuXa8=
  - secure: eRXRUIxaepn9mNSq3YwjAatyQuOFuKCmLQpv3Xk2EWo3qAvIxNVDzdrMvVaX3E8YEUAxqkieWaULWsIp4PqkCBbOdvdgFb97EnxWXXbiHV0W0AEt3IjiM3Ao+WYSuQUNtgHL4v4ItM3g0g8gfUsCYdb7h/JxA2NSH6T5/CaMUWRzSJUknW9DKMH+8RrrN4zxE5iFpjOVPBzinWN9EYm/otyligmOf/zexPMohjwohYNYgKoatyJGYQdigdUS3rNgQPUjD1jAcz8lCFfRnesLU+BBXCm+YL7GGZ/0VtlmIijqefyYcIyU95JQyBGAJp20gqV9tWzs2cKCjkv3Ep0NpAREIWvAihCdpoTeMG5X3YWXg4wqjkhUQQZX3PvP5S0vFb9yKeaFVehWv+ECWEz03h2TGxHwDAWrSbJ1ANOlNCpUoTs946ICkw27zNKnB7r/As9PjcTpHx8dMHi2ZxSR3Uz2Pa8nN/TzvmMxgDoavSkOzoZF+RsP7y5CDuEaEl8iNnvd39kKozn079uZpNg6ijfC2bgmo0ngQN1s0Mw4wyuoe9TVp+WPL2my1P+pDLPO3vCP+4hCqbeTCW3kHC6bbCaXTm4UQM3/3asa5roe+ob0xJsP8qLGqP8Xpl3rwFJyH4PQ/gql+YEbFmHF3beGcmuYcUzCDZqHHx/vbFuKtLg=
  - secure: V4konUGMX//pMfRauwZus5BKwMA2z+tK/j/CnZFQGGbeyxkCRY3FroJZ/tAIOaQs/Q4RcS7YpcQDyP83VBbT3TecEzUIsSsL2nDmhXFHSSSaKwjSRqF9zG5/ubhGaZNcGZd8RLGW5GvPUWprUo08jBnxzEYOSPYtM8qaqn/wFhaGQgMlWC48udP/yGroxU0qMZkXs7KAA02YsdF7/J/m665hXWj3ATCywA5dB9fVZl5DrYr6Sm6kVM+cHmJ0wtWGALajcjezWklft1ZnSKJGCoyjkP4pq1vGG5QUg3Nj+0eJwHU4d1hGhaUnN7GPUEPoeiqqd9IzUZKteArWVIW/RKnarxE9Za/GP38/osj86RboA0WjL6pmnEy4ZWe8P9QltEptouM843uWJLcpcs52T8Lyuww0gefrPPXdadBKQJNe/nyTlCnrbIDCa4PbZoJ+3SlOjDR5ER2P6TyNOmHNRyZT4uQcrYvguUoZgkVvgqVLPlxaByBcCHK+CyI4MH+hlrVg/djZEQWja5ivkc3nS2Hk7cFdjGUmdHRhNIKoAfdajhsH22mhL6seYiT+Reb/UUl67/xx8tie42f9AaKzxl/p07c6H+JlCNB4+vdshCsbHgUQ70Nfsv1a+KnlzE1MHBntNzBkbS8i4tB7Svl1n9JQPzn+lkPSdwKolcDCagM=
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build/html
  on:
    branch: master
