name: digicampipe
channels:
- astropy
- conda-forge
- cta-observatory
dependencies:
- aenum
- python=3.6
- astropy
- astroquery
- ctapipe-extra=0.2.*
- cython
- docopt
- fitsio
- h5py
- hdf5
- humanize
- iminuit
- jupyter
- matplotlib
- numba
- numpy
- opencv
- photutils
- pip
- protobuf
- pyqt<=5.11
- pytest=3.*
- PyYAML=3.13
- scikit-learn
- scikit-image
- scipy
- sphinx_rtd_theme
- traitlets
- pip:
  - msgpack
  - peakutils==1.0.3
  - pytest-benchmark==3.1.1
  - pytest-runner==3.0
  - recommonmark==0.4.0
  - secretstorage
  - sphinx-automodapi
  - git+https://github.com/iminuit/probfit.git
  - https://github.com/cta-sst-1m/protozfitsreader/archive/v1.4.2.tar.gz
  - git+https://github.com/cta-observatory/pyhessio.git
  - git+https://github.com/cta-observatory/ctapipe.git@a1fc0eb62612e0be4f121a37b5791049eb7adc2a
  - git+https://github.com/cta-sst-1m/CTS.git
  - git+https://github.com/dstndstn/astrometry.net.git
  - git+https://github.com/cta-sst-1m/histogram.git
  - git+https://github.com/uvemas/ViTables.git
